---
- name: Add stesie/libv8 apt repository
  apt_repository:
    repo: ppa:stesie/libv8

- name: Install libv8-7.5
  apt:
    name: "libv8-7.5"

- name: Install phpv8-js
  apt:
    name: "php-v8"

- name: Add php-v8js extension to php.ini
  shell: >
    echo "extension=v8js.so" >> {{ php_ini_path }}

- name: Reload php-fpm
  service:
    name: 'php{{ php_version }}-fpm'
    state: reloaded

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
